- type: job
  id: MinerProfession
  name: шахтёр
  description: Шахтёр, добро пожаловать в замечательные шахты НТ, прозванные Лаваленд. Здесь вы будете крушить камни, сражаться с монстрами и умирать.
  playTimeTracker: JobMinerProfession
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000 #5 часов
  startingGear: LavaMinerProfessionGear
  icon: "JobIconShaftMiner"
  supervisors: job-supervisors-qm
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Cargo
  wage: 70


- type: startingGear
  id: LavaMinerProfessionGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist #Униформ
    back: ClothingBackpackDuffelSalvage #Рюкзак
    shoes: ClothingShoesBootsSalvage #Ботинки
    head: ClothingHeadHatHardhatYellowDark  #Голова
    eyes: ClothingEyesGlassesCheapSunglasses    #Очки                             ClothingBeltSalvageWebbing ClothingBeltSecurityFilled
    gloves: ClothingHandsGlovesColorBlack #Перчатки
    outerClothing: ClothingOuterWinterMiner #Верх
    id: MinerPDA
    ears: ClothingHeadsetMining #Уши
    belt: BoxSurvival #Поясь
    pocket1: LavaPhoneInstrument
    pocket2: AppraisalTool


- type: randomHumanoidSettings
  id: LavaSettingsMinerProfession
  randomizeName: true
  components:
    - type: Loadout
      prototypes: [LavaMinerProfessionGear]
    - type: GhostRole
      name: 'Шахтёр'
      description: "Шахтёр, добро пожаловать в замечательные шахты НТ, прозванные Лаваленд. Здесь вы будете крушить камни, сражаться с монстрами и умирать. "
    - type: GhostTakeoverAvailable

- type: entity
  id: LavaRandomHumanoidSpawnerMinerProfession
  name: Шахтёр
  components:
    - type: Sprite
      sprite: Markers/jobs.rsi
      state: cburn
    - type: RandomHumanoidSpawner
      settings: LavaSettingsMinerProfession
